anu_bullying_pair_labels = {
    1: 'G1A1: hit with knees',
    2: 'G2A1: hit with head',
    3: 'G3A1: punch to face',
    4: 'G4A1: punch to body',
    5: 'G5A1: cover mouth',
    6: 'G6A1: pinch neck',
    7: 'G7A1: slap',
    8: 'G8A1: kicking',
    9: 'G9A1: pushing',
    10: 'G10A1: pierce others',
    11: 'G11A1: pull hairs',
    12: 'G12A1: drag other person',
    13: 'G13A1: pull collar',
    14: 'G14A1: swing others',
    15: 'G15A1: beat with elbow',
    16: 'G16A1: knoch over',
    17: 'G17A1: hit with object',
    18: 'G18A1: point to person',
    19: 'G19A1: cuff ear',
    20: 'G20A1: pinch arms',
    21: 'G21A1: use cigarette to burn',
    22: 'G22A1: sidekick person',
    23: 'G23A1: cast to person',
    24: 'G24A1: shoot person',
    25: 'G25A1: stab person',
    26: 'G26A1: wave knife to others',
    27: 'G27A1: splash liquid on person',
    28: 'G28A1: stumble person',
    29: 'G29A1: step on foot',
    30: 'G30A1: touch pocket',
    31: 'G31A1: bite person',
    32: 'G32A1: take picture for others',
    33: 'G33A1: spiting to person',
    34: 'G34A1: chop person',
    35: 'G35A1: take chair while other sitting',
    36: 'G36A1: pat on head',
    37: 'G37A1: pinch face',
    38: 'G38A1: pinch body',
    39: 'G39A1: follow person',
    40: 'G40A1: belt person',
    41: 'G1A2: nod head',
    42: 'G2A2: bow',
    43: 'G3A2: shake hands',
    44: 'G4A2: rock-paper-scissors',
    45: 'G5A2: touch elbows',
    46: 'G6A2: wave hand',
    47: 'G7A2: fist bumping',
    48: 'G8A2: pat on back',
    49: 'G9A2: giving object',
    50: 'G10A2: exchange object',
    51: 'G11A2: clapping; hushing',
    52: 'G12A2: drink water; brush teeth',
    53: 'G13A2: stand up; jump up',
    54: 'G14A2: take off a hat; play a phone',
    55: 'G15A2: take a selfie; wipe face',
    56: 'G16A2: cross hands in front; throat-slitting',
    57: 'G17A2: crawling; open bottle',
    58: 'G18A2: sneeze; yawn',
    59: 'G19A2: self-cutting with knife; take off headphone',
    60: 'G20A2: stretch oneself; flick hair',
    61: 'G21A2: thumb up; thumb down',
    62: 'G22A2: make ok sign; make victory sign',
    63: 'G23A2: cutting nails; cutting paper',
    64: 'G24A2: squat down; toss a coin',
    65: 'G25A2: fold paper; ball up paper',
    66: 'G26A2: play magic cube; surrender',
    67: 'G27A2: apply cream on face; apply cream on hand',
    68: 'G28A2: put on bag; take off bag',
    69: 'G29A2: put object into bag; take object out of bag',
    70: 'G30A2: open a box; yelling',
    71: 'G31A2: arm circles; arm swings',
    72: 'G32A2: whisper',
    73: 'G33A2: clapping each other',
    74: 'G34A2: running; vomiting',
    75: 'G35A2: walk apart',
    76: 'G36A2: headache; back pain',
    77: 'G37A2: walk toward',
    78: 'G38A2: falling down; chest pain',
    79: 'G39A2: walk and hold person',
    80: 'G40A2: cheers and drink',
}

ntu120_code_labels = {
    1: 'drink water',
    2: 'eat meal/snack"',
    3: "brushing teeth",
    4: "brushing hair",
    5: "drop",
    6: "pickup",
    7: "throw",
    8: "sitting down",
    9: "standing up (from sitting position)",
    10: "clapping",
    11: "reading",
    12: "writing",
    13: "tear up paper",
    14: "wear jacket",
    15: "take off jacket",
    16: "wear a shoe",
    17: "take off a shoe",
    18: "wear on glasses",
    19: "take off glasses",
    20: "put on a hat/cap",
    21: "take off a hat/cap",
    22: "cheer up",
    23: "hand waving",
    24: "kicking something",
    25: "reach into pocket",
    26: "hopping (one foot jumping)",
    27: "jump up",
    28: "make a phone call/answer phone",
    29: "playing with phone/tablet",
    30: "typing on a keyboard",
    31: "pointing to something with finger",
    32: "taking a selfie",
    33: "check time (from watch)",
    34: "rub two hands together",
    35: "nod head/bow",
    36: "shake head",
    37: "wipe face",
    38: "salute",
    39: "put the palms together",
    40: "cross hands in front (say stop)",
    41: "sneeze/cough",
    42: "staggering",
    43: "falling",
    44: "touch head (headache)",
    45: "touch chest (stomachache/heart pain)",
    46: "touch back (backache)",
    47: "touch neck (neckache)",
    48: "nausea or vomiting condition",
    49: "use a fan (with hand or paper)/feeling warm",
    50: "punching/slapping other person",
    51: "kicking other person",
    52: "pushing other person",
    53: "pat on back of other person",
    54: "point finger at the other person",
    55: "hugging other person",
    56: "giving something to other person",
    57: "touch other person's pocket",
    58: "handshaking",
    59: "walking towards each other",
    60: "walking apart from each other",
    61: "put on headphone",
    62: "take off headphone",
    63: "shoot at the basket",
    64: "bounce ball",
    65: "tennis bat swing",
    66: "juggling table tennis balls",
    67: "hush (quite)",
    68: "flick hair",
    69: "thumb up",
    70: "thumb down",
    71: "make ok sign",
    72: "make victory sign",
    73: "staple book",
    74: "counting money",
    75: "cutting nails",
    76: "cutting paper (using scissors)",
    77: "snapping fingers",
    78: "open bottle",
    79: "sniff (smell)",
    80: "squat down",
    81: "toss a coin",
    82: "fold paper",
    83: "ball up paper",
    84: "play magic cube",
    85: "apply cream on face",
    86: "apply cream on hand back",
    87: "put on bag",
    88: "take off bag",
    89: "put something into a bag",
    90: "take something out of a bag",
    91: "open a box",
    92: "move heavy objects",
    93: "shake fist",
    94: "throw up cap/hat",
    95: "hands up (both hands)",
    96: "cross arms",
    97: "arm circles",
    98: "arm swings",
    99: "running on the spot",
    100: "butt kicks (kick backward)",
    101: "cross toe touch",
    102: "side kick",
    103: "yawn",
    104: "stretch oneself",
    105: "blow nose",
    106: "hit other person with something",
    107: "wield knife towards other person",
    108: "knock over other person (hit with body)",
    109: "grab other person’s stuff",
    110: "shoot at other person with a gun",
    111: "step on foot",
    112: "high-five",
    113: "cheers and drink",
    114: "carry something with other person",
    115: "take a photo of other person",
    116: "follow other person",
    117: "whisper in other person’s ear",
    118: "exchange things with other person",
    119: "support somebody with hand",
    120: "finger-guessing game (playing rock-paper-scissors)",
}

bly_labels = {
    1: 'G1A1: hit with knees',
    2: 'G2A1: hit with head',
    3: 'G3A1: punch to face',
    4: 'G4A1: punch to body',
    5: 'G5A1: cover mouth',
    6: 'G6A1: pinch neck',
    7: 'G7A1: slap',
    8: 'G8A1: kicking',
    9: 'G9A1: pushing',
    10: 'G10A1: pierce others',
    11: 'G11A1: pull hairs',
    12: 'G12A1: drag other person',
    13: 'G13A1: pull collar',
    14: 'G14A1: swing others',
    15: 'G15A1: beat with elbow',
    16: 'G16A1: knoch over',
    17: 'G17A1: hit with object',
    18: 'G18A1: point to person',
    19: 'G19A1: cuff ear',
    20: 'G20A1: pinch arms',
    21: 'G21A1: use cigarette to burn',
    22: 'G22A1: sidekick person',
    23: 'G23A1: cast to person',
    24: 'G24A1: shoot person',
    25: 'G25A1: stab person',
    26: 'G26A1: wave knife to others',
    27: 'G27A1: splash liquid on person',
    28: 'G28A1: stumble person',
    29: 'G29A1: step on foot',
    30: 'G30A1: touch pocket',
    31: 'G31A1: bite person',
    32: 'G33A1: spiting to person',
    33: 'G34A1: chop person',
    34: 'G35A1: take chair while other sitting',
    35: 'G36A1: pat on head',
    36: 'G37A1: pinch face',
    37: 'G38A1: pinch body',
    38: 'G40A1: belt person',
}

anubis_ind_actions = {
    0: 'hit with knees',
    1: 'hit with head',
    2: 'punch to face',
    3: 'punch to body',
    4: 'cover mouth',
    5: 'strangling neck',
    6: 'slap',
    7: 'kicking',
    8: 'pushing',
    9: 'pierce arms',
    10: 'pull hairs',
    11: 'drag other person (other resist)',
    12: 'pull collar',
    13: 'shake others',
    14: 'beat with elbow',
    15: 'knock over',
    16: 'hit with object',
    17: 'point to person',
    18: 'lift ear',
    19: 'pinch arms',
    20: 'use cigarette to burn',
    21: 'sidekick person',
    22: 'pick and throw an object to person',
    23: 'shoot person',
    24: 'stab person',
    25: 'wave knife to others',
    26: 'splash liquid on person',
    27: 'stumble person',
    28: 'step on foot',
    29: 'pickpocketing',
    30: 'bite person',
    31: 'take picture for others (sneakily)',
    32: 'spiting to person',
    33: 'chop (cut) person',
    34: 'take chair while other sitting',
    35: 'hit the head with hand',
    36: 'pinch face with two hands',
    37: 'pinch body (not arm)',
    38: 'follow person',
    39: 'belt person',
    40: 'nod head',
    41: 'bow',
    42: 'shake hands',
    43: 'rock-paper-scissors',
    44: 'touch elbows',
    45: 'wave hand',
    46: 'fist bumping',
    47: 'pat on shoulders',
    48: 'giving object',
    49: 'exchange object',
    50: 'clapping and hushing',
    51: 'drink water',
    52: 'brush teeth',
    53: 'stand up',
    54: 'jump up',
    55: 'take off a hat',
    56: 'play a phone',
    57: 'take a selfie',
    58: 'wipe face',
    59: 'cross hands in front',
    60: 'throat-slitting',
    61: 'crawling',
    62: 'open bottle',
    63: 'sneeze',
    64: 'yawn',
    65: 'self-cutting with knife',
    66: 'take off headphone',
    67: 'stretch oneself',
    68: 'flick hair',
    69: 'thumb up',
    70: 'thumb down',
    71: 'make ok sign',
    72: 'make victory sign',
    73: 'cutting nails',
    74: 'cutting paper',
    75: 'squat down',
    76: 'toss a coin',
    77: 'fold paper',
    78: 'ball up paper',
    79: 'play magic cube',
    80: 'surrender',
    81: 'apply cream on face',
    82: 'apply cream on hand',
    83: 'put on bag',
    84: 'take off bag',
    85: 'put object into bag',
    86: 'take object out of bag',
    87: 'open a box and yelling',
    88: 'arm circles',
    89: 'arm swings',
    90: 'whisper',
    91: 'clapping each other',
    92: 'running',
    93: 'vomiting',
    94: 'walk apart',
    95: 'headache',
    96: 'back pain',
    97: 'walk form apart to together',
    98: 'falling down',
    99: 'chest pain',
    100: 'support with arms for old people walking',
    101: 'cheers and drink'}
